"""create initial smart library schema

Revision ID: d42b878aa019
Revises: 
Create Date: 2026-07-23 00:39:59.569269
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'd42b878aa019'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.Enum('super_admin', 'library_owner', 'staff', 'student', name='role_name', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('libraries',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'suspended', name='library_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('primary_owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_libraries_approved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_owner_user_id'], ['users.id'], name=op.f('fk_libraries_primary_owner_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_libraries'))
    )
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_libraries_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_libraries_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_libraries_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_libraries_primary_owner_user_id'), ['primary_owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_libraries_status'), ['status'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('platform_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_platform_settings_updated_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_platform_settings_key'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], name=op.f('fk_user_roles_assigned_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_user_sessions_refresh_token_hash'))
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('account_invitations',
    sa.Column('library_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'library_owner', 'staff', 'student', name='invitation_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'expired', 'revoked', name='invitation_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_account_invitations_invited_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_account_invitations_library_id_libraries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_invitations')),
    sa.UniqueConstraint('library_id', 'email', 'status', name='uq_invitation_library_email_status'),
    sa.UniqueConstraint('token_hash', name=op.f('uq_account_invitations_token_hash'))
    )
    with op.batch_alter_table('account_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_invitations_library_id'), ['library_id'], unique=False)

    op.create_table('announcements',
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Enum('normal', 'important', name='announcement_priority', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('audience', sa.Enum('all_students', 'active_students', 'pending_fee_students', name='announcement_audience', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'published', 'expired', 'archived', name='announcement_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('expires_at IS NULL OR scheduled_for IS NULL OR expires_at > scheduled_for', name=op.f('ck_announcements_announcement_schedule_valid')),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_announcements_author_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_announcements_library_id_libraries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index('ix_announcement_library_status_publish', ['library_id', 'status', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_status'), ['status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('library_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_audit_logs_library_id_libraries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_audit_library_created', ['library_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)

    op.create_table('floors',
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_floors_library_id_libraries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_floors')),
    sa.UniqueConstraint('library_id', 'code', name='uq_floor_library_code')
    )
    with op.batch_alter_table('floors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_floors_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_floors_library_id'), ['library_id'], unique=False)

    op.create_table('library_memberships',
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'library_owner', 'staff', 'student', name='membership_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('invited', 'active', 'suspended', 'left', name='membership_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_library_memberships_library_id_libraries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_library_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_library_memberships')),
    sa.UniqueConstraint('library_id', 'user_id', name='uq_membership_library_user')
    )
    with op.batch_alter_table('library_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_memberships_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_memberships_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('library_settings',
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('weekly_off_days', sa.JSON(), nullable=False),
    sa.Column('default_monthly_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_due_day', sa.Integer(), nullable=False),
    sa.Column('payment_grace_days', sa.Integer(), nullable=False),
    sa.Column('receipt_prefix', sa.String(length=24), nullable=False),
    sa.Column('allow_seat_change_requests', sa.Boolean(), nullable=False),
    sa.Column('require_seat_request_reason', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_reminders_enabled', sa.Boolean(), nullable=False),
    sa.Column('notify_pending_payments', sa.Boolean(), nullable=False),
    sa.Column('notify_seat_requests', sa.Boolean(), nullable=False),
    sa.Column('notify_maintenance_seats', sa.Boolean(), nullable=False),
    sa.Column('email_announcement_copy', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_library_settings_library_id_libraries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_library_settings')),
    sa.UniqueConstraint('library_id', name=op.f('uq_library_settings_library_id'))
    )
    op.create_table('shifts',
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('crosses_midnight', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('start_time <> end_time', name=op.f('ck_shifts_start_and_end_differ')),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_shifts_library_id_libraries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts')),
    sa.UniqueConstraint('library_id', 'name', name='uq_shift_library_name')
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shifts_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shifts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_shifts_library_id'), ['library_id'], unique=False)

    op.create_table('students',
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('enrollment_number', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('guardian_name', sa.String(length=160), nullable=True),
    sa.Column('guardian_phone', sa.String(length=32), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('preferred_language', sa.String(length=16), nullable=False),
    sa.Column('joined_on', sa.Date(), nullable=False),
    sa.Column('left_on', sa.Date(), nullable=True),
    sa.Column('monthly_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'left', 'suspended', name='student_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('monthly_fee >= 0', name=op.f('ck_students_monthly_fee_non_negative')),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_students_library_id_libraries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_students_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('library_id', 'email', name='uq_student_library_email'),
    sa.UniqueConstraint('library_id', 'enrollment_number', name='uq_student_library_enrollment')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_user_id'), ['user_id'], unique=True)

    op.create_table('announcement_reads',
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('announcement_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name=op.f('fk_announcement_reads_announcement_id_announcements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_announcement_reads_library_id_libraries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_announcement_reads_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcement_reads')),
    sa.UniqueConstraint('announcement_id', 'student_id', name='uq_announcement_read_student')
    )
    with op.batch_alter_table('announcement_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcement_reads_announcement_id'), ['announcement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_reads_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_reads_student_id'), ['student_id'], unique=False)

    op.create_table('fee_records',
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('billing_month', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('late_fee_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('unpaid', 'partially_paid', 'paid', 'waived', 'cancelled', name='fee_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('generated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('waived_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('waived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('base_amount >= 0', name=op.f('ck_fee_records_fee_base_amount_non_negative')),
    sa.CheckConstraint('discount_amount >= 0', name=op.f('ck_fee_records_fee_discount_non_negative')),
    sa.CheckConstraint('late_fee_amount >= 0', name=op.f('ck_fee_records_fee_late_amount_non_negative')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_fee_records_fee_total_amount_non_negative')),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], name=op.f('fk_fee_records_generated_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_fee_records_library_id_libraries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_fee_records_student_id_students'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['waived_by_user_id'], ['users.id'], name=op.f('fk_fee_records_waived_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fee_records')),
    sa.UniqueConstraint('library_id', 'student_id', 'billing_month', name='uq_fee_record_student_month')
    )
    with op.batch_alter_table('fee_records', schema=None) as batch_op:
        batch_op.create_index('ix_fee_record_library_month_status', ['library_id', 'billing_month', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_records_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_records_student_id'), ['student_id'], unique=False)

    op.create_table('seats',
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('floor_id', sa.Uuid(), nullable=False),
    sa.Column('seat_number', sa.String(length=64), nullable=False),
    sa.Column('seat_type', sa.Enum('standard', 'premium', 'cabin', 'accessible', name='seat_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('operational_status', sa.Enum('available', 'maintenance', 'blocked', name='seat_operational_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status_note', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], name=op.f('fk_seats_floor_id_floors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_seats_library_id_libraries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seats')),
    sa.UniqueConstraint('library_id', 'seat_number', name='uq_seat_library_number')
    )
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.create_index('ix_seat_library_floor_status', ['library_id', 'floor_id', 'operational_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_seats_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_seats_floor_id'), ['floor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seats_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seats_operational_status'), ['operational_status'], unique=False)

    op.create_table('payment_reminders',
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('fee_record_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', 'sms', 'email', name='reminder_channel', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'failed', name='reminder_delivery_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('message_snapshot', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fee_record_id'], ['fee_records.id'], name=op.f('fk_payment_reminders_fee_record_id_fee_records'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_payment_reminders_library_id_libraries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], name=op.f('fk_payment_reminders_sent_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_payment_reminders_student_id_students'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_reminders'))
    )
    with op.batch_alter_table('payment_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_reminders_fee_record_id'), ['fee_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_reminders_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_reminders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_reminders_student_id'), ['student_id'], unique=False)

    op.create_table('payment_transactions',
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('fee_record_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('cash', 'upi', 'bank_transfer', 'card', 'other', name='payment_method', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'refunded', name='payment_transaction_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reference_number', sa.String(length=120), nullable=True),
    sa.Column('external_transaction_id', sa.String(length=160), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payment_transactions_payment_amount_positive')),
    sa.ForeignKeyConstraint(['fee_record_id'], ['fee_records.id'], name=op.f('fk_payment_transactions_fee_record_id_fee_records'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_payment_transactions_library_id_libraries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], name=op.f('fk_payment_transactions_recorded_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_payment_transactions_student_id_students'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_transactions')),
    sa.UniqueConstraint('external_transaction_id', name=op.f('uq_payment_transactions_external_transaction_id'))
    )
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_payment_library_paid_at', ['library_id', 'paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_fee_record_id'), ['fee_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_reference_number'), ['reference_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_student_id'), ['student_id'], unique=False)

    op.create_table('seat_allocations',
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('seat_id', sa.Uuid(), nullable=False),
    sa.Column('shift_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'cancelled', name='allocation_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('shift_name', sa.String(length=100), nullable=False),
    sa.Column('shift_start_time', sa.Time(), nullable=False),
    sa.Column('shift_end_time', sa.Time(), nullable=False),
    sa.Column('shift_crosses_midnight', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('close_reason', sa.Text(), nullable=True),
    sa.Column('allocated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allocated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('closed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('previous_allocation_id', sa.Uuid(), nullable=True),
    sa.Column('transfer_group_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_seat_allocations_allocation_date_range_valid')),
    sa.CheckConstraint('shift_start_time <> shift_end_time', name=op.f('ck_seat_allocations_allocation_shift_times_differ')),
    sa.ForeignKeyConstraint(['allocated_by_user_id'], ['users.id'], name=op.f('fk_seat_allocations_allocated_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], name=op.f('fk_seat_allocations_closed_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_seat_allocations_library_id_libraries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_allocation_id'], ['seat_allocations.id'], name=op.f('fk_seat_allocations_previous_allocation_id_seat_allocations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], name=op.f('fk_seat_allocations_seat_id_seats'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_seat_allocations_shift_id_shifts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_seat_allocations_student_id_students'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seat_allocations'))
    )
    with op.batch_alter_table('seat_allocations', schema=None) as batch_op:
        batch_op.create_index('ix_allocation_seat_conflict_lookup', ['library_id', 'seat_id', 'status', 'start_date', 'end_date'], unique=False)
        batch_op.create_index('ix_allocation_student_conflict_lookup', ['library_id', 'student_id', 'status', 'start_date', 'end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_allocations_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_allocations_seat_id'), ['seat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_allocations_shift_id'), ['shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_allocations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_allocations_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_allocations_transfer_group_id'), ['transfer_group_id'], unique=False)

    op.create_table('seat_status_events',
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('seat_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('available', 'maintenance', 'blocked', name='seat_previous_operational_status', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('to_status', sa.Enum('available', 'maintenance', 'blocked', name='seat_new_operational_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('effective_until IS NULL OR effective_until > effective_from', name=op.f('ck_seat_status_events_status_period_valid')),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('fk_seat_status_events_changed_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_seat_status_events_library_id_libraries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], name=op.f('fk_seat_status_events_seat_id_seats'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seat_status_events'))
    )
    with op.batch_alter_table('seat_status_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seat_status_events_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_status_events_seat_id'), ['seat_id'], unique=False)

    op.create_table('receipts',
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('receipt_number', sa.String(length=80), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('voided_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_receipts_library_id_libraries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_receipts_student_id_students'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment_transactions.id'], name=op.f('fk_receipts_transaction_id_payment_transactions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voided_by_user_id'], ['users.id'], name=op.f('fk_receipts_voided_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipts')),
    sa.UniqueConstraint('library_id', 'receipt_number', name='uq_receipt_library_number'),
    sa.UniqueConstraint('transaction_id', name=op.f('uq_receipts_transaction_id'))
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_student_id'), ['student_id'], unique=False)

    op.create_table('seat_change_requests',
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('request_number', sa.String(length=64), nullable=False),
    sa.Column('current_allocation_id', sa.Uuid(), nullable=True),
    sa.Column('preferred_seat_id', sa.Uuid(), nullable=True),
    sa.Column('preferred_floor_id', sa.Uuid(), nullable=True),
    sa.Column('preferred_shift_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='seat_request_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('resulting_allocation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status <> 'rejected' OR admin_note IS NOT NULL", name=op.f('ck_seat_change_requests_rejected_request_has_note')),
    sa.ForeignKeyConstraint(['current_allocation_id'], ['seat_allocations.id'], name=op.f('fk_seat_change_requests_current_allocation_id_seat_allocations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_seat_change_requests_library_id_libraries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['preferred_floor_id'], ['floors.id'], name=op.f('fk_seat_change_requests_preferred_floor_id_floors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preferred_seat_id'], ['seats.id'], name=op.f('fk_seat_change_requests_preferred_seat_id_seats'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preferred_shift_id'], ['shifts.id'], name=op.f('fk_seat_change_requests_preferred_shift_id_shifts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resulting_allocation_id'], ['seat_allocations.id'], name=op.f('fk_seat_change_requests_resulting_allocation_id_seat_allocations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_seat_change_requests_reviewed_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_seat_change_requests_student_id_students'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seat_change_requests')),
    sa.UniqueConstraint('library_id', 'request_number', name='uq_seat_request_library_number')
    )
    with op.batch_alter_table('seat_change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seat_change_requests_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_change_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_change_requests_student_id'), ['student_id'], unique=False)
        batch_op.create_index('uq_pending_seat_request_per_student', ['library_id', 'student_id'], unique=True, sqlite_where=sa.text("status = 'pending'"), postgresql_where=sa.text("status = 'pending'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seat_change_requests', schema=None) as batch_op:
        batch_op.drop_index('uq_pending_seat_request_per_student', sqlite_where=sa.text("status = 'pending'"), postgresql_where=sa.text("status = 'pending'"))
        batch_op.drop_index(batch_op.f('ix_seat_change_requests_student_id'))
        batch_op.drop_index(batch_op.f('ix_seat_change_requests_status'))
        batch_op.drop_index(batch_op.f('ix_seat_change_requests_library_id'))

    op.drop_table('seat_change_requests')
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_student_id'))
        batch_op.drop_index(batch_op.f('ix_receipts_library_id'))

    op.drop_table('receipts')
    with op.batch_alter_table('seat_status_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seat_status_events_seat_id'))
        batch_op.drop_index(batch_op.f('ix_seat_status_events_library_id'))

    op.drop_table('seat_status_events')
    with op.batch_alter_table('seat_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seat_allocations_transfer_group_id'))
        batch_op.drop_index(batch_op.f('ix_seat_allocations_student_id'))
        batch_op.drop_index(batch_op.f('ix_seat_allocations_status'))
        batch_op.drop_index(batch_op.f('ix_seat_allocations_shift_id'))
        batch_op.drop_index(batch_op.f('ix_seat_allocations_seat_id'))
        batch_op.drop_index(batch_op.f('ix_seat_allocations_library_id'))
        batch_op.drop_index('ix_allocation_student_conflict_lookup')
        batch_op.drop_index('ix_allocation_seat_conflict_lookup')

    op.drop_table('seat_allocations')
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transactions_student_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_reference_number'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_library_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_fee_record_id'))
        batch_op.drop_index('ix_payment_library_paid_at')

    op.drop_table('payment_transactions')
    with op.batch_alter_table('payment_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_reminders_student_id'))
        batch_op.drop_index(batch_op.f('ix_payment_reminders_status'))
        batch_op.drop_index(batch_op.f('ix_payment_reminders_library_id'))
        batch_op.drop_index(batch_op.f('ix_payment_reminders_fee_record_id'))

    op.drop_table('payment_reminders')
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seats_operational_status'))
        batch_op.drop_index(batch_op.f('ix_seats_library_id'))
        batch_op.drop_index(batch_op.f('ix_seats_floor_id'))
        batch_op.drop_index(batch_op.f('ix_seats_deleted_at'))
        batch_op.drop_index('ix_seat_library_floor_status')

    op.drop_table('seats')
    with op.batch_alter_table('fee_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_records_student_id'))
        batch_op.drop_index(batch_op.f('ix_fee_records_status'))
        batch_op.drop_index(batch_op.f('ix_fee_records_library_id'))
        batch_op.drop_index('ix_fee_record_library_month_status')

    op.drop_table('fee_records')
    with op.batch_alter_table('announcement_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcement_reads_student_id'))
        batch_op.drop_index(batch_op.f('ix_announcement_reads_library_id'))
        batch_op.drop_index(batch_op.f('ix_announcement_reads_announcement_id'))

    op.drop_table('announcement_reads')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_user_id'))
        batch_op.drop_index(batch_op.f('ix_students_status'))
        batch_op.drop_index(batch_op.f('ix_students_library_id'))
        batch_op.drop_index(batch_op.f('ix_students_deleted_at'))

    op.drop_table('students')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shifts_library_id'))
        batch_op.drop_index(batch_op.f('ix_shifts_is_active'))
        batch_op.drop_index(batch_op.f('ix_shifts_deleted_at'))

    op.drop_table('shifts')
    op.drop_table('library_settings')
    with op.batch_alter_table('library_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_library_memberships_status'))
        batch_op.drop_index(batch_op.f('ix_library_memberships_library_id'))

    op.drop_table('library_memberships')
    with op.batch_alter_table('floors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_floors_library_id'))
        batch_op.drop_index(batch_op.f('ix_floors_deleted_at'))

    op.drop_table('floors')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_library_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('ix_audit_library_created')
        batch_op.drop_index('ix_audit_entity')

    op.drop_table('audit_logs')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_status'))
        batch_op.drop_index(batch_op.f('ix_announcements_library_id'))
        batch_op.drop_index(batch_op.f('ix_announcements_deleted_at'))
        batch_op.drop_index('ix_announcement_library_status_publish')

    op.drop_table('announcements')
    with op.batch_alter_table('account_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_invitations_library_id'))
        batch_op.drop_index(batch_op.f('ix_account_invitations_email'))

    op.drop_table('account_invitations')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))

    op.drop_table('user_sessions')
    op.drop_table('user_roles')
    op.drop_table('platform_settings')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_libraries_status'))
        batch_op.drop_index(batch_op.f('ix_libraries_primary_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_libraries_name'))
        batch_op.drop_index(batch_op.f('ix_libraries_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_libraries_code'))

    op.drop_table('libraries')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))

    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
